/*
TEST FILE FOR ft_strchr.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please
#include <string.h>

char *ft_strchr(char *s, int c);


// Autogenerated test function for ft_strchr
int	T_ft_strchr(void)
{
	char	a[23] = "coucou je suis heureux";
	if (ft_strchr(a, 'c') != strchr(a, 'c'))
		return (1);
	if (ft_strchr(a, 'j') != strchr(a, 'j'))
		return (2);
	if (ft_strchr(a, 'f') != strchr(a, 'f'))
		return (3);
	if (ft_strchr("", 'c') != strchr("", 'c'))
		return (4);
	return (0);
}
