/*
TEST FILE FOR ft_lstlast_bonus.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include "../libft.h"

t_list *ft_lstlast(t_list *lst);

// Autogenerated test function for ft_lstlast
int	T_ft_lstlast(void)
{
	t_list	*a;
	t_list	*b;
	t_list	*c;
	t_list	*d;
	t_list	*e;
	t_list	*f;
	int		i;

	i = 1;
	a = ft_lstnew(&i);
	b = ft_lstnew(&i);
	c = ft_lstnew(&i);
	d = ft_lstnew(&i);
	e = ft_lstnew(&i);

	f = a;
	ft_lstadd_front(&f, b);
	ft_lstadd_front(&f, c);
	ft_lstadd_front(&f, d);
	ft_lstadd_front(&f, e);

	if (ft_lstlast(f) != a)
		return (1);
	if (ft_lstlast(0) != 0)
		return (1);
	return (0);
}
