/*
TEST FILE FOR ft_memset.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please
#include <string.h>

void *ft_memset(void *s, int c, unsigned int n);


// Autogenerated test function for ft_memset
int	T_ft_memset(void)
{
	char	a[100];
	char	b[100];
	ft_memset(a, 'a', 100);
	memset(b, 'a', 100);
	if (memcmp(a, b, 100) != 0)
		return (1);
	bzero(a, 100);
	bzero(b, 100);
	memset(b + 2, 'b', 40);
	ft_memset(a + 2, 'b', 40);
	if (memcmp(a, b, 100) != 0)
		return (2);
	return (0);
}
