/*
TEST FILE FOR ft_isdigit.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please

int ft_isdigit(int c);


// Autogenerated test function for ft_isdigit
int	T_ft_isdigit(void)
{
	if (!ft_isdigit('a')
		&& !ft_isdigit('B')
		&& !ft_isdigit('/')
		&& ft_isdigit('3'))
		return (0);		// the test passes
	return (1);			// the test does not, display error code
}
