/*
TEST FILE FOR ft_strjoin.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include <string.h>

char	*ft_strjoin(char const *s1, char const *s2);


// Autogenerated test function for ft_strjoin
int	T_ft_strjoin(void)
{
	if (memcmp(ft_strjoin("coucou", " je suis heureux"), "coucou je suis heureux", 23) != 0)
		return (1);
	if (memcmp(ft_strjoin("", "coucou je suis heureux"), "coucou je suis heureux", 23) != 0)
		return (2);
	if (memcmp(ft_strjoin("coucou je suis heureux", ""), "coucou je suis heureux", 23) != 0)
		return (3);
	if (memcmp(ft_strjoin("", ""), "", 1) != 0)
		return (4);
	return (0);
}
