/*
TEST FILE FOR ft_putstr_fd.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include <unistd.h>
#include <fcntl.h>

void ft_putstr_fd(char *s, int fd);


// Autogenerated test function for ft_putstr_fd
int	T_ft_putstr_fd(void)
{
	int	f;

	f = open("./test_gen/TEMP_out.txt", O_WRONLY + O_CREAT);
	if (f == -1)
		return (1);
	ft_putstr_fd("coucou je suis heureux", f);
	if (close(f) != 0)
		return (2);
	return (0);		// the test passes
}
