/*
TEST FILE FOR ft_atoi.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please
#include <stdlib.h>

int ft_atoi(const char *str);

// Autogenerated test function for ft_atoi
int	T_ft_atoi(void)
{
	char	tab[8][12] = {"42", "0", "-42", "2147483647", "-2147483648", "   ", " -+-42", "    \t42"};
	for (int i = 0; i < 8 ; i++)
	{
		if (atoi(tab[i]) != ft_atoi(tab[i]))
		{
			printf("For \"%s\"\tatoi: %d\tft_atoi: %d\n", tab[i], atoi(tab[i]), ft_atoi(tab[i]));
			return (1);
		}
	}
	return (0);
}
