/*
TEST FILE FOR ft_itoa.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please
#include <string.h>

char *ft_itoa(int n);


// Autogenerated test function for ft_itoa
int	T_ft_itoa(void)
{
	if (strcmp(ft_itoa(42), "42") != 0)
		return (1);
	if (strcmp(ft_itoa(-42), "-42") != 0)
		return (2);
	if (strcmp(ft_itoa(2147483647), "2147483647") != 0)
		return (3);
	if (strcmp(ft_itoa(-2147483648), "-2147483648") != 0)
		return (4);
	if (strcmp(ft_itoa(0), "0") != 0)
		return (5);
	return (0);
}
