/*
TEST FILE FOR ft_isascii.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please

int ft_isascii(int c);


// Autogenerated test function for ft_isascii
int	T_ft_isascii(void)
{
	if (ft_isascii('a')
		&& ft_isascii('B')
		&& ft_isascii('/')
		&& !ft_isascii(128)
		&& !ft_isascii(-1)
		&& ft_isascii(0)
		&& ft_isascii('\n')
		&& ft_isascii('3'))
		return (0);		// the test passes
	return (1);			// the test does not, display error code
}
