/*
TEST FILE FOR ft_memcpy.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please
#include <string.h>

void *ft_memcpy(void *dest, const void *src, unsigned int n);


// Autogenerated test function for ft_memcpy
int	T_ft_memcpy(void)
{
	char	a[100];
	char	b[100];

	memset(a, 'a', 100);
	memset(b, 'b', 100);
	ft_memcpy(a, b, 42);
	if (memcmp(a, b, 42) != 0)
		return (1);
	int	i = 0;
	while (a[i] == 'b')
		i++;
	if (i != 42)
		return (2);
	memset(a, 'a', 100);
	memset(b, 'b', 100);
	ft_memcpy(a, b, 0);
	memset(b, 'a', 100);
	if (memcmp(a, b, 2) != 0)
		return (3);
	return (0);
}
