/*
TEST FILE FOR ft_isalnum.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please

int ft_isalnum(int c);


// Autogenerated test function for ft_isalnum
int	T_ft_isalnum(void)
{
	if (ft_isalnum('a')
		&& ft_isalnum('B')
		&& !ft_isalnum('/')
		&& ft_isalnum('3'))
		return (0);		// the test passes
	return (1);			// the test does not, display error code
}
