/*
TEST FILE FOR ft_strmapi.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include <string.h>

char *ft_strmapi(char const *s, char (*f)(unsigned int, char));
int ft_tolower(int c);


static char	func(unsigned int i, char c)
{
	i += 1;
	if (c == '\0')
		return ('@');
	return (ft_tolower(c));
}
// Autogenerated test function for ft_strmapi
int	T_ft_strmapi(void)
{
	if (memcmp("coucou je suis heureux", ft_strmapi("COUCOU je SUIS hEUrEUx", &func), 23) == 0)
		return (0);		// the test passes
	return (1);			// the test does not, display error code
}
