/*
TEST FILE FOR ft_strlcat.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include <string.h>

unsigned int ft_strlcat(char *dest, char *src, unsigned int size);


// Autogenerated test function for ft_strlcat
int	T_ft_strlcat(void)
{
	char	a[21]="coucoujesu\0\0\0\0\0\0\0\0\0\0";
	char	b[11]="is heureux";
	char	c[21]="coucoujesu\0\0\0\0\0\0\0\0\0\0";
	int		i;
	i = ft_strlcat(a, b, 10);
	if (memcmp(a, "coucoujesu\0\0\0\0\0", 15) != 0 && i == 20)
		return (1);
	i = ft_strlcat(a, b, 15);
	if (memcmp(a, "coucoujesuis h\0", 15) != 0 && i == 20)
		return (2);
	i = ft_strlcat(c, b, 0);
	if (i != 10)
		return (3);
	return (0);
}
