/*
TEST FILE FOR ft_strlcat.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include <string.h>
#include <unistd.h>

unsigned int ft_strlcat(char *dest, char *src, unsigned int size);


// Autogenerated test function for ft_strlcat
int	T_ft_strlcat(void)
{
	char	a[50]="coucoujesu\0\0\0\0\0\0\0\0\0\0";
	char	b[50]="is heureux";
	char	c[50]="coucoujesu\0\0\0\0\0\0\0\0\0\0";
	int		i;
	//int		j;
	//i = strlcat(a, b, 10);
	i = ft_strlcat(c, b, 10);
	if (memcmp(a, c, 21) != 0 || i != 20)
		return (1);
	//i = strlcat(a, b, 15);
	i = ft_strlcat(c, b, 15);
	//printf("%d\n",i);
	if (memcmp(c, "coucoujesuis h", 15) != 0 || i != 20)
		return (2);
	i = ft_strlcat(c, b, 0);
	//j = strlcat(c, b, 0);
	if (i != 10)
		return (3);
	bzero(a, 50);
	bzero(b, 50);
	bzero(c, 50);
	memset(a, 'a', 10);
	memset(b, 'b', 10);
	memset(c, 'a', 10);
	//i = strlcat(a, b, 2);
	i = ft_strlcat(c, b, 2);
	if (memcmp(a, c, 21) != 0 || i != 12)
		return (4);
	//i = strlcat(a, b, 50);
	i = ft_strlcat(c, b, 50);
	if (memcmp("aaaaaaaaaabbbbbbbbbb", c, 21) != 0 || i != 20)
		return (5);
	char aa[17] = "coucou";
	char cc[17] = "coucou";
	//i = strlcat(aa, "lorem ipsum dolor sit amet", 5);
	i = ft_strlcat(cc, "lorem ipsum dolor sit amet", 5);
	printf("\t\033[1;31m WARN \033[0m : strlcat n'est pas censé réecrire le \\0 de dest si size > strlen(dest),\n\tmais aucun moyen ne permet pour le moment de le verifier \n");
	if (memcmp(aa, cc, 7) != 0 || i != 31)
		return (6);
	return (0);
}
