/*
TEST FILE FOR ft_lstmap_bonus.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include "../libft.h"

t_list *ft_lstmap(t_list *lst, void *(*f)(void *), void (*del)(void *));

void	deletion(void *a)
{
	*((int*)a) = 0;
}

void	*m(void *n)
{
	return (n);
}

void	*nulle(void *n)
{
	if (n)
		return (0);
	return (n);
}

// Autogenerated test function for ft_lstmap
int	T_ft_lstmap(void)
{
	t_list	*a;
	t_list	*b;
	t_list	*c;
	t_list	*d;
	int	i;
	int	j;

	i = 1;
	j = 2;
	a = ft_lstnew(&i);
	b = ft_lstnew(&j);
	ft_lstadd_back(&a, b);

	c = ft_lstmap(a, &m, &deletion);
	if ((*(int*)c->content) + *(int*)(c->next)->content != 3)
		return (1);
	ft_lstclear(&c, &deletion);

	c = ft_lstmap(a, &m, NULL);
	ft_lstclear(&c, &deletion);

	c = ft_lstmap(a, NULL, &deletion);
	ft_lstclear(&c, &deletion);

	c = ft_lstmap(NULL, &m, &deletion);

	d = ft_lstmap(a, &nulle, &deletion);
	if (d != 0)
		return (2);
	ft_lstclear(&a, &deletion);
	return (0);
}
