/*
TEST FILE FOR ft_putendl_fd.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please

void ft_putendl_fd(char *s, int fd);


// Autogenerated test function for ft_putendl_fd
int	T_ft_putendl_fd(void)
{
	if (ft_putendl_fd())
		return (0);		// the test passes
	return (1);			// the test does not, displays error code
}
