/*
TEST FILE FOR ft_calloc.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please
#include <string.h>
#include <stdlib.h>
#include <malloc.h>

void *ft_calloc(unsigned int nmemb, unsigned int size);


// Autogenerated test function for ft_calloc
int	T_ft_calloc(void)
{
	//1
	void	*a = calloc(3, 3);
	char	b[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
	if (memcmp(a, b, 9) != 0)
		return (1);
	//2
	if (ft_calloc(2147483648, 2147483648) != NULL)
	{
		return (2);
	}
	//3
	if (malloc_usable_size(a) != malloc_usable_size(malloc(9)))
	{
		return (3);
	}
	return (0);
}
