/*
TEST FILE FOR ft_strrchr.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please
#include <string.h>

char *ft_strrchr(char *s, int c);


// Autogenerated test function for ft_strrchr
int	T_ft_strrchr(void)
{
	char	a[23] = "coucou je suis heureux";
	if (ft_strrchr(a, 'c') != strrchr(a, 'c'))
		return (1);
	if (ft_strrchr(a, 'j') != strrchr(a, 'j'))
		return (2);
	if (ft_strrchr(a, 'f') != strrchr(a, 'f'))
		return (3);
	if (ft_strrchr("", 'c') != strrchr("", 'c'))
		return (4);
	if (ft_strrchr("", 0) != strrchr("", 0))
		return (4);
	return (0);
}
