/*
TEST FILE FOR ft_tolower.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please

int ft_tolower(int c);


// Autogenerated test function for ft_tolower
int	T_ft_tolower(void)
{
	if (ft_tolower('A') == 'a'
		&& ft_tolower('a') == 'a'
		&& ft_tolower('1') == '1')
		return (0);		// the test passes
	return (1);			// the test does not, display error code
}
