/*
TEST FILE FOR ft_lstclear.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include "../libft.h"

void ft_lstclear(t_list **lst, void (*del)(void *));

void	deletion(void *a)
{
	*((int*)a) = 0;
}

// Autogenerated test function for ft_lstclear
int	T_ft_lstclear(void)
{
	t_list	*a;
	t_list	*b;
	t_list	*c;
	t_list	*d;
	t_list	*e;
	t_list	*f;
	int		i;
	int		j;
	int		k;
	int		l;
	int		m;

	i = 1;
	j = 2;
	k = 3;
	l = 5;
	m = 12;
	a = ft_lstnew(&i);
	b = ft_lstnew(&j);
	c = ft_lstnew(&k);
	d = ft_lstnew(&l);
	e = ft_lstnew(&m);

	f = a;
	ft_lstadd_back(&f, b);
	ft_lstadd_back(&f, c);
	ft_lstadd_back(&f, d);
	ft_lstadd_back(&f, e);

	ft_lstclear(&a, &deletion);
	ft_lstclear(&a, NULL);
	ft_lstclear(NULL, &deletion);
	ft_lstclear(NULL, NULL);
	return (i + j + k + l + m);
}
