/*
TEST FILE FOR ft_bzero.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include <string.h>
#include <stdlib.h>

void ft_bzero(void *s, unsigned int n);

// Autogenerated test function for ft_bzero
int	T_ft_bzero(void)
{
	char	a[100];
	char	b[100];

	//1
	memset(a, 'h', 100);
	memset(b, 'h', 100);
	ft_bzero(a, 0);
	if (memcmp(a, b, 100) != 0)
		return (1);
	//2
	ft_bzero(a, 100);
	bzero(b, 100);
	if (memcmp(a, b, 100) != 0)
		return (2);
	//3
	memset(a, 'h', 100);
	memset(b, 'h', 100);
	ft_bzero(a, 42);
	bzero(b, 42);
	if (memcmp(a, b, 100) != 0)
		return (3);
	//4
	memset(a, 'h', 100);
	memset(b, 'h', 100);
	a[0] = 0;
	b[0] = 0;
	ft_bzero(a, 42);
	bzero(b, 42);
	if (memcmp(a, b, 100) != 0)
		return (4);
	return (0);
}


