/*
TEST FILE FOR ft_strncmp.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please
#include <string.h>

int ft_strncmp(char *s1, const char *s2, unsigned int n);


// Autogenerated test function for ft_strncmp
int	T_ft_strncmp(void)
{
	if (ft_strncmp("aac", "aaa", 3) != strncmp("aac", "aaa", 3))
		return (1);
	if (ft_strncmp("aaa", "aaa", 2) != strncmp("aaa", "aaa", 2))
		return (2);
	if (ft_strncmp("aac", "aaa", 2) != strncmp("aac", "aaa", 2))
		return (3);
	if (ft_strncmp("aac", "aaa", 0) != strncmp("aac", "aaa", 0))
		return (4);
	if (ft_strncmp("aac", "aaa", 6) != strncmp("aac", "aaa", 6))
		return (5);
	if (ft_strncmp("aaa", "aaa", 6) != strncmp("aaa", "aaa", 6))
		return (6);
	if (ft_strncmp("aaa\200b", "aaa\0", 6) != strncmp("aaa\200b", "aaa\0", 6))
		return (7);
	return (0);
}
