/*
TEST FILE FOR ft_split.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please
#include <stdlib.h>
#include <string.h>


char **ft_split(const char *str, char c);


// Autogenerated test function for ft_split
int	T_ft_split(void)
{
	char	**splited;
	char	res[5][7] = {"coucou", "je", "suis", "heureux"};

	splited = ft_split("         coucou je suis heureux      ", ' ');
	char	**tofree = splited;
	int	i=-1;
	while (i++ < 4)
	{
		if (memcmp(res[i], splited[i], strlen(res[i])) != 0)
			return (1);
		free(splited[i]);
	}
	free(tofree);
	char	a[] = "coucou je suis heureux";
	splited = ft_split(a, '-');
	if (memcmp(a, *splited, 22) != 0)
		return (2);
	free(*splited);
	free(splited);
	if (*ft_split("", '-') != 0)
		return (3);
	return (0);
}
