/*
TEST FILE FOR ft_striteri.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include <string.h>

void ft_striteri(char *s, char (*f)(unsigned int, char));
int ft_tolower(int c);


static char	func(unsigned int i, char c)
{
	i += 1;
	if (c == '\0')
		return ('@');
	return (ft_tolower(c));
}
// Autogenerated test function for ft_striteri
int	T_ft_striteri(void)
{
	char	a[] = "COUCOU je SUIS hEUrEUx";
	ft_striteri(a, &func);
	if (memcmp("coucou je suis heureux", a, 23) == 0)
		return (0);		// the test passes
	return (1);			// the test does not, display error code
}
