/*
TEST FILE FOR ft_strdup.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please
#include <string.h>

char *ft_strdup(char const *src);


// Autogenerated test function for ft_strdup
int	T_ft_strdup(void)
{
	if (memcmp(ft_strdup("coucou je suis heureux"), "coucou je suis heureux", 23) != 0)
		return (1);
	if (memcmp(ft_strdup(""), "", 1) != 0)
		return (2);
	return (0);
}
