/*
TEST FILE FOR ft_lstnew.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include "../libft.h"

t_list *ft_lstnew(void *content);


// Autogenerated test function for ft_lstnew
int	T_ft_lstnew(void)
{
	int	c;
	t_list	*a;

	c = 1;
	a = ft_lstnew(&c);
	if (a == 0)
		return (-1);
	if (*(int*)(a->content) != 1)
		return (1);
	if (a->next != 0)
		return (2);
	return (0);
}
