/*
TEST FILE FOR ft_isalpha.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please

int ft_isalpha(int c);


// Autogenerated test function for ft_isalpha
int	T_ft_isalpha(void)
{
	if (ft_isalpha('a')
		&& ft_isalpha('B')
		&& !ft_isalpha('/')
		&& !ft_isalpha('3'))
		return (0);		// the test passes
	return (1);			// the test does not, display error code
}
