/*
TEST FILE FOR ft_lstsize_bonus.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include "../libft.h"

int ft_lstsize(t_list *lst);


// Autogenerated test function for ft_lstsize
int	T_ft_lstsize(void)
{
	t_list	*a;
	t_list	*b;
	t_list	*c;
	t_list	*d;
	t_list	*e;
	int		i;

	i = 1;
	a = ft_lstnew(&i);
	b = ft_lstnew(&i);
	c = ft_lstnew(&i);
	d = ft_lstnew(&i);
	e = ft_lstnew(&i);

	ft_lstadd_front(&a, b);
	ft_lstadd_front(&a, c);
	ft_lstadd_front(&a, d);
	ft_lstadd_front(&a, e);

	if (ft_lstsize(a) != 5)
		return (1);
	if (ft_lstsize(NULL) != 0)
		return (2);
	return (0);
}
