/*
TEST FILE FOR ft_isprint.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please

int ft_isprint(int c);


// Autogenerated test function for ft_isprint
int	T_ft_isprint(void)
{
	if (ft_isprint('a')
		&& ft_isprint('B')
		&& ft_isprint('/')
		&& ft_isprint(' ')
		&& !ft_isprint('\n')
		&& !ft_isprint('\0')
		&& !ft_isprint('\t')
		&& ft_isprint('3'))
		return (0);		// the test passes
	return (1);			// the test does not, display error code
}
