/*
TEST FILE FOR ft_lstdelone_bonus.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include "../libft.h"

void ft_lstdelone(t_list *lst, void (*del)(void *));

void	deletion(void *a)
{
	*((int*)a) = 0;
}

// Autogenerated test function for ft_lstdelone
int	T_ft_lstdelone(void)
{
	void	*a;
	int		i;

	i = 1;
	a = ft_lstnew(&i);
	ft_lstdelone(a, &deletion);
	ft_lstdelone(NULL, NULL);
	return (i);
}
