/*
TEST FILE FOR ft_lstadd_front_bonus.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include <stdlib.h>
#include "../libft.h"

void ft_lstadd_front(t_list **lst, t_list *new);


// Autogenerated test function for ft_lstadd_front
int	T_ft_lstadd_front(void)
{
	t_list	*a;
	t_list	*b;
	int	i = 1;
	int	j = 2;
	a = ft_lstnew(&i);
	b = ft_lstnew(&j);
	ft_lstadd_front(&a, b);
	if (*((int*)a->content) != 2)
		return (1);
	if (*((int*)(a->next)->content) != 1)
		return (2);
	ft_lstadd_front(NULL, b);
	ft_lstadd_front(&a, NULL);
	free(a->next);
	free(a);
	a = NULL;
	ft_lstadd_front(&a, NULL);
	return (0);
}
