/*
TEST FILE FOR ft_itoa.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES:

#include <stdio.h> // do not remove please
#include <string.h>
#include <stdlib.h>
#include <malloc.h>

char *ft_itoa(int n);


// Autogenerated test function for ft_itoa
int	T_ft_itoa(void)
{
	char	*a = malloc(420000);
	if (a == NULL)
		return (-1);
	memset(a, '1', 420000);
	free(a);
	a = ft_itoa(42);
	if (memcmp(a, "42", 3) != 0 || malloc_usable_size(a) != malloc_usable_size(malloc(3 * sizeof(char))))
		return (1);
	free(a);
	a = ft_itoa(-42);
	if (memcmp(a, "-42", 4) != 0 || malloc_usable_size(a) != malloc_usable_size(malloc(4 * sizeof(char))))
		return (2);
	free(a);
	a = ft_itoa(2147483647);
	if (memcmp(a, "2147483647", 11) != 0 || malloc_usable_size(a) != malloc_usable_size(malloc(11 * sizeof(char))))
		return (3);
	free(a);
	a = ft_itoa(-2147483648);
	if (memcmp(a, "-2147483648", 12) != 0 || malloc_usable_size(a) != malloc_usable_size(malloc(12 * sizeof(char))))
		return (4);
	free(a);
	a = ft_itoa(0);
	if (memcmp(a, "0", 2) != 0 || malloc_usable_size(a) != malloc_usable_size(malloc(2 * sizeof(char))))
		return (5);
	free(a);
	return (0);
}
