/*
TEST FILE FOR ft_strtrim.c
Generated with the test_generator utility
*/

// Write your dependencies after the :
// do not uncomment
//DEPENDENCIES: libft.a

#include <stdio.h> // do not remove please
#include <string.h>

char *ft_strtrim(char const *s1, char const *set);


// Autogenerated test function for ft_strtrim
int	T_ft_strtrim(void)
{
	if (strncmp("coucou_je_suis_heureux", ft_strtrim("2841230948 coucou_je_suis_heureux 210478123", "1234567890 "), 22) == 0 &&
		strncmp("c0uc0u j3 suis heureux", ft_strtrim("2841230948 c0uc0u j3 suis heureux 210478123", "1234567890 "), 22) == 0)
		return (0);		// the test passes
	return (1);			// the test does not, display error code
}
